language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

install:
  - pip install coveralls flake8

script:
  - coverage run --source=awslogs setup.py test
  - python setup.py install
  - which awslogs
  - awslogs --help
  - flake8 awslogs

after_success:
  coveralls
